name: Warchest Battle

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go Linter
        run: |
          go get -u golang.org/x/lint/golint

      - name: Lint
        run: |
          golint -set_exit_status ./...

      - name: Run Unittests
        run: make covreport

      # Ref: https://github.com/lluuiissoo/go-testcoverage
      - name: Quality Gate - Test coverage shall be above threshold
        env:
          TESTCOVERAGE_THRESHOLD: 80
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ matrix.os }}-${{ matrix.go-version }}
          path: |
            coverage.out
            coverage.html
